# Generated by Django 4.0.5 on 2022-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_teacher_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Class'),
        ),
    ]
