# Generated by Django 4.0.5 on 2022-06-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
