# Generated by Django 4.0.5 on 2022-06-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
