# Generated by Django 4.0.5 on 2022-06-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_custommember_role_custommember_is_manager_and_more'),
        ('main', '0008_delete_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('classroom', models.CharField(choices=[('A', 'CLASS-A'), ('B', 'CLASS-B'), ('C', 'CLASS-C')], max_length=1, verbose_name='Classroom')),
                ('approval', models.BooleanField(default=False, verbose_name='Approval')),
                ('attending_students', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('attending_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.teacher')),
            ],
        ),
    ]
