# Generated by Django 4.0.5 on 2022-06-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='attending_students',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
