# Generated by Django 4.0.5 on 2022-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_schoolclass_attending_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='attending_students',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='attending_students',
            field=models.ManyToManyField(null=True, to='main.student'),
        ),
    ]
