# Generated by Django 4.0.5 on 2022-06-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_schoolclass_attending_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='approval',
        ),
    ]
