# Generated by Django 4.0.5 on 2022-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_schoolclass_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='classroom',
            field=models.CharField(choices=[('A', 'CLASS-A'), ('B', 'CLASS-B'), ('C', 'CLASS-C')], max_length=1, unique=True, verbose_name='Classroom'),
        ),
    ]
