# Generated by Django 4.0.5 on 2022-06-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_custommember_role_custommember_is_manager_and_more'),
        ('main', '0017_alter_schoolclass_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='attending_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('attending_teacher', 'attending_student')},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='attending_students',
        ),
    ]
