# Generated by Django 4.0.5 on 2022-06-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_studentclass_schoolclass_stu_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='stu_no',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
