# Generated by Django 4.0.5 on 2022-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_schoolclass_attending_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='attending_students',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='attendingstudent',
            field=models.ManyToManyField(related_name='schoolclass', to='main.student'),
        ),
    ]
