# Generated by Django 4.0.5 on 2022-06-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_schoolclass_attending_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
