# Generated by Django 4.0.5 on 2022-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_event_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descriptions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
