# Generated by Django 4.0.5 on 2022-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_event_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
    ]
