# Generated by Django 4.0.5 on 2022-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_event_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='classroom',
            field=models.CharField(choices=[('A', 'CLASS-A'), ('B', 'CLASS-B'), ('C', 'CLASS-C'), ('D', 'CLASS-D'), ('E', 'CLASS-E'), ('F', 'CLASS-F'), ('G', 'CLASS-G'), ('H', 'CLASS-H'), ('I', 'CLASS-I'), ('J', 'CLASS-J')], max_length=1, unique=True, verbose_name='Classroom'),
        ),
    ]
