# Generated by Django 4.0.5 on 2022-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
