# Generated by Django 4.0.5 on 2022-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommember',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Parent'), (2, 'Teacher'), (3, 'Manager')], default=1, null=True),
        ),
    ]
