# Generated by Django 4.0.5 on 2022-07-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_custommember_role_custommember_is_manager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
